services:
  sync-pyth:
    build: .
    # Env file containing the minio credentials
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - s3_network
    entrypoint: ["poetry", "run", "python", "-m", "s3_synchroniser.main"]
    command: >
      --endpoint_url http://minio:9000
      --bucket_name test
      --local_path /app/data_to_sync
      --create_bucket
    volumes:
      - ./data_to_sync:/app/data_to_sync

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    # https://github.com/minio/minio/issues/18389
    healthcheck:
      test: ["CMD", "sh", "-c", "mc ready local"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 1s
    networks:
      - s3_network

networks:
  s3_network:
    driver: bridge
